var N = null;var sourcesIndex = {};
sourcesIndex["common"] = {"name":"","files":["lib.rs"]};
sourcesIndex["core_mods"] = {"name":"","files":["anchor.rs","attest.rs","blob.rs","did.rs","lib.rs","master.rs","revoke.rs"]};
sourcesIndex["dock_node"] = {"name":"","files":["chain_spec.rs","cli.rs","command.rs","lib.rs","rpc.rs","service.rs"]};
sourcesIndex["dock_runtime"] = {"name":"","files":["lib.rs","weight_to_fee.rs"]};
sourcesIndex["forked_pallet_democracy"] = {"name":"","files":["conviction.rs","default_weight.rs","lib.rs","types.rs","vote.rs","vote_threshold.rs"]};
sourcesIndex["poa"] = {"name":"","files":["lib.rs","runtime_api.rs"]};
sourcesIndex["poa_rpc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["price_feed"] = {"name":"","files":["lib.rs","runtime_api.rs","util.rs"]};
sourcesIndex["price_feed_rpc"] = {"name":"","files":["lib.rs"]};
sourcesIndex["simple_democracy"] = {"name":"","files":["lib.rs"]};
sourcesIndex["token_migration"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
